
# I want empty lines!
Layout/EmptyLines:
  Enabled: false

Layout/MultilineOperationIndentation:
  Exclude:
    - spec/renderer/*_spec.rb

# We all have wide screen monitors, so why only 80?
Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Style/RegexpLiteral:
  AllowInnerSlashes: false

Style/Encoding:
  Enabled: false

Style/PercentQLiterals:
  Exclude:
    - lib/bade/generator.rb

Style/NumericPredicate:
  Enabled: false

# We are supporting Ruby 2.3 with frozen strings, so not working
Style/EmptyLiteral:
  Enabled: false

# Still not working as expected
Style/Documentation:
  Enabled: false

# Only matches the good part of Perl backrefs ($1, $2, ...), not the bad part ($', $`, $<, ...)
Style/PerlBackrefs:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*.rb

Style/RedundantBegin:
  Enabled: false

# We adopted raise instead of fail.
Style/SignalException:
  EnforcedStyle: only_raise

# WTF: why is default 10?
Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 40
  Exclude:
    - spec/**/*_spec.rb

# It will be obvious which code is complex, Rubocop should only lint simple
# rules for us.
Metrics/AbcSize:
  Enabled: false

# It will be obvious which code is complex, Rubocop should only lint simple
# rules for us.
Metrics/CyclomaticComplexity:
  Enabled: false

# It will be obvious which code is complex, Rubocop should only lint simple
# rules for us.
Metrics/PerceivedComplexity:
  Enabled: false


# Having these make it easier to *not* forget to add one when adding a new
# value and you can simply copy the previous line.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Lint/RequireParentheses:
  Enabled: true

Lint/LiteralInInterpolation:
  Exclude:
  - spec/**/*.rb

Lint/EmptyWhen:
  Enabled: false







Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
