name: Run tests
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13] # macos-13 is the only macOS runner that runs on x64 arch (CRuby < 2.6 does not support macos-arm64)
        ruby: [3.3, 3.2, 3.1, 3.0, 2.7, 2.6, 2.5]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop
